#Tree work

spring:
  application:
    name: DemoSpring
  datasource:
    url: jdbc:mysql://localhost:3306/badminton_management
    username: root
    password:

  # jpa là một cơ chế giúp chúng ta tương tác với cơ sở dữ liệu một cách dễ dàng hơn
  jpa:
    show-sql: true # Hiển thị câu lệnh SQL
    hibernate:
      ddl-auto: none # Tạo bảng tự động
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

server:
  port: 8088 #hiển thị